pipeline {
    agent any

    environment {
        IMAGE_NAME = "anuj0109/portfolio-site:v1"
    }

    stages {
        stage('Code Pull') {
            steps {
                git branch: 'main', url: 'https://github.com/Anuj-0109/portfolio-devops.git'
            }
        }

        stage('Image Build') {
            steps {
                dir('portfolio-devops') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Push Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh 'docker push $IMAGE_NAME'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('portfolio-devops') {
                    sh 'KUBECONFIG=/var/lib/jenkins/.kube/config kubectl apply -f deployment.yaml'
                    sh 'kubectl apply -f service.yaml'
                    sh '''
                        export KUBECONFIG=/var/lib/jenkins/.kube/config
                
                        # ensure pods pick up the newly pushed image (force rolling restart)
                        kubectl rollout restart deployment portfolio-deployment
                        kubectl rollout status deployment portfolio-deployment --timeout=120s
                      '''
                     sh '''
                          pkill -f "kubectl port-forward --address 0.0.0.0 svc/portfolio-service 30081:8081" || true
                          nohup kubectl port-forward --address 0.0.0.0 svc/portfolio-service 30081:8081 \
                            > /var/log/portfolio-portforward.log 2>&1 &
                              sleep 2
                              ss -tlnp | grep 30081 || true
                              tail -n 20 /var/log/portfolio-portforward.log || true
                        '''
                }
            }
        }
    }
}
